plugins:
  - '@dotcom-tool-kit/commitlint'
  - '@dotcom-tool-kit/component'
  - '@dotcom-tool-kit/eslint'
  - '@dotcom-tool-kit/husky-npm'
  - '@dotcom-tool-kit/lint-staged-npm'
  - '@dotcom-tool-kit/node-test'
  - '@dotcom-tool-kit/prettier'
  - '@dotcom-tool-kit/typescript'

commands:

  # Empty to avoid a TypeScript build step
  build:local: []

  git:precommit:
    - LintStaged

  # Empty to avoid a TypeScript build step
  run:local: []

  test:local:
    - Eslint
    - TypeScript
    - NodeTest

  test:ci:
    - Eslint
    - TypeScript
    - NodeTest

options:
  plugins:
    '@dotcom-tool-kit/circleci':
      cimgNodeVersions:
        - '24.0'
        - '22.13'
        - '20.18'
  tasks:
    Eslint:
      files: '**/*.js'
    Prettier:
      files: '**/*.js'
    TypeScript:
      configPath: jsconfig.json
